name: Build V3 - Version and release on PR

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: master

      - name: Label changes
        if: steps.cpr.outputs.pull-request-number
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.cpr.outputs.pull-request-number }}
          sync-labels: true

      - name: Get PR labels
        if: steps.cpr.outputs.pull-request-number
        id: pr-labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.cpr.outputs.pull-request-number }}
            });
            const labels = pr.data.labels.map(label => label.name);
            core.setOutput('labels', JSON.stringify(labels));
            core.setOutput('has-audio', labels.includes('audio'));
            core.setOutput('has-cicd', labels.includes('cicd'));
            
      - name: Bump version and push tag
        if: steps.pr-labels.outputs.has-audio == 'true'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          release_branches: master
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_prerelease_bump: patch
          tag_prefix: ''
          
      - name: Release Changelog Builder
        if: steps.pr-labels.outputs.has-audio == 'true'
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          outputFile: "CHANGELOG.MD"
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                  "title": "## 🎹 Audio",
                  "labels": ["audio", "sound", "sounds"]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": ["fix", "fixes"]
                },
                {
                  "title": "## 🔩 CI/CD (you don't care)",
                  "labels": ["ci", "cicd", "cd"]
                },
                {
                  "key": "tests",
                  "title": "## 🧪 Tests",
                  "labels": ["test", "tests"]
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|cicd|cd|docs|feat|fix|fixes|perf|refactor|revert|style|test|tests|audio|sound|sounds){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
            
      - name: See CHANGELOG
        if: steps.pr-labels.outputs.has-audio == 'true'
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"

      - name: Release
        if: steps.pr-labels.outputs.has-audio == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag_version.outputs.new_version }}
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          body: ${{ steps.changelog.outputs.changelog }}
          body_path: CHANGELOG.MD
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          make_latest: true
          
      - name: Enable Auto-Merge on Pull Request
        if: steps.pr-labels.outputs.has-cicd == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          # This will only merge after all required status checks pass